[package]
name = "rdoc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
color-eyre = "0.6.5"
colored = "3.0.0"
fst = "0.4.7"
regex-automata = "0.4.13"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
